version: '3.8'

services:
  # RAG Flask application
  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
     - ./.env
    volumes:
      - ./data:/app/data
    depends_on:
      - qdrant
      - searxng
      - mongodb
    restart: unless-stopped

  # Qdrant vector database
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped
    
  # SearXNG web search service
  searxng:
    image: searxng/searxng:latest
    ports:
      - "8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - BASE_URL=http://localhost:8080/
      - INSTANCE_NAME=RAG Web Search
      - AUTOCOMPLETE=google
      - ENABLE_METRICS=0
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
      
  # MongoDB for chat history
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=ragapp
    restart: unless-stopped

volumes:
  qdrant_data:
  mongodb_data:
